name: Nightly Build

on:
  schedule:
    - cron:  '0 0 * * *'
  push:

jobs:
  build:
    runs-on: ubuntu-20.04
    
    container: qmkfm/base_container
    
    steps:
    - name: upgrade ARM GCC
      run: |
        wget -q https://developer.arm.com/-/media/Files/downloads/gnu-rm/10-2020q4/gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.bz2 -O - | tar xj --strip-components=1 -C / && rm -rf /arm-none-eabi/share/ /share/
        
    - name: Checkout build repo
      uses: actions/checkout@v2

    - name: Checkout qmk_firmware
      uses: actions/checkout@v2
      with:
        submodules: recursive
        repository: qmk/qmk_firmware
        path: qmk_firmware
        
    - name: obtain all tags
      uses: actions/checkout@v2
      with:
        repository: qmk/qmk_firmware
        path: qmk_firmware
        fetch-depth: 0
    
    - name: Revert MIDI_VELOCITY_MIN
      run: |
        sed -i '350d' qmk_firmware/quantum/quantum_keycodes.h
        sed -i '350 c\    MI_VEL_1 = MIDI_VELOCITY_MIN,' qmk_firmware/quantum/quantum_keycodes.h     
      
    - name: Remove ".noci"
      run: |
        find . -name ".noci" -type f -delete
        
    - name: ARM GCC version
      run: |
        arm-none-eabi-gcc --version
        
    - name: Build
      working-directory: qmk_firmware
      env:
        MAKEFLAGS: '-j3 --output-sync'
      run: |
        make all:via
        
    - name: Copy
      run: |
        cp -f qmk_firmware/*.bin .
        cp -f qmk_firmware/*.hex .
      
    - name: Update Readme
      shell: bash "{0}"
      run: |
        echo -e "# VIA enabled QMK compiled HEX and BIN files\n\nThis has been compiled on $(git -C $PWD/qmk_firmware describe --abbrev=0 --tags)" > README.md

    - name: Commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Nightly Build
