name: Nightly Build

on:
  schedule:
    - cron:  '0 0 * * *'
  push:

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Manual trigger'
  
jobs:
  build:
    runs-on: ubuntu-20.04
    
    container: qmkfm/base_container
    
    steps:
    - name: upgrade ARM GCC
      run: |
        wget -q https://developer.arm.com/-/media/Files/downloads/gnu-rm/8-2019q3/RC1.1/gcc-arm-none-eabi-8-2019-q3-update-linux.tar.bz2 -O - | tar xj --strip-components=1 -C / && rm -rf /arm-none-eabi/share/ /share/
        
    - name: upgrade ARM GCC
      run: |
        wget -q https://blog.zakkemble.net/download/avr-gcc-8.3.0-x64-linux.tar.bz2 -O - | tar xj --strip-components=1 -C / && rm -rf /avr/share/ /share/
    
    
    - name: Checkout build repo
      uses: actions/checkout@v2

    - name: Checkout qmk_firmware
      uses: actions/checkout@v2
      with:
        submodules: recursive
        repository: qmk/qmk_firmware
        path: qmk_firmware
        
    - name: obtain all tags
      uses: actions/checkout@v2
      with:
        repository: qmk/qmk_firmware
        path: qmk_firmware
        fetch-depth: 0
    
#     - name: Revert MIDI_VELOCITY_MIN
#      run: |
#        sed -i '334d' qmk_firmware/quantum/quantum_keycodes.h
#        sed -i '334 c\    MI_VEL_1 = MIDI_VELOCITY_MIN,' qmk_firmware/quantum/quantum_keycodes.h     
    
        
    - name: Remove Sirius/uni660
      run: |
        rm -r qmk_firmware/keyboards/sirius/uni660
        
    - name: Add define VIA_HAS_BROKEN_KEYCODES
      run: |
        directory="qmk_firmware/keyboards"
        for dir in $(ls -d ${directory}/*/); do
            if [ -d "${dir}keymaps/via" ]; then
                if grep -l "BLUETOOTH =" "${dir}rules.mk"; then
                    echo "#define VIA_HAS_BROKEN_KEYCODES" >> "${dir}config.h"
                fi
            fi
        done
      shell: bash
      
    - name: Remove ".noci"
      run: |
        find . -name ".noci" -type f -delete
        
    - name: ARM GCC version
      run: |
        arm-none-eabi-gcc --version
      
    - name: AVR GCC version
      run: |
        which avr-gcc
        avr-gcc --version
        
    - name: Build
      working-directory: qmk_firmware
      env:
        MAKEFLAGS: '-j3 --output-sync'
      run: |
        make all:via -j
        
    - name: Copy
      run: |
        cp -f qmk_firmware/*.bin .
        cp -f qmk_firmware/*.hex .
      
    - name: Update Readme
      shell: bash "{0}"
      run: |
        echo -e "# VIA enabled QMK compiled HEX and BIN files\n\nThis has been compiled on $(git -C $PWD/qmk_firmware describe --abbrev=0 --tags)" > README.md

    - name: Commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Nightly Build
