name: Nightly Build

on:
  schedule:
    - cron:  '0 0 * * *'
  push:

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Manual trigger'
  
jobs:
  build:
    runs-on: ubuntu-20.04
    
    container: qmkfm/qmk_cli
    
    steps:
    - name: install libfl2
      run: |
        apt-get update
        apt-get install --no-install-recommends -y libfl2
    
    - name: Checkout build repo
      uses: actions/checkout@v2

    - name: Checkout qmk_firmware
      uses: actions/checkout@v2
      with:
        submodules: recursive
        repository: qmk/qmk_firmware
        path: qmk_firmware
        
    - name: obtain all tags
      uses: actions/checkout@v2
      with:
        repository: qmk/qmk_firmware
        path: qmk_firmware
        fetch-depth: 0    
        
    - name: Remove Sirius/uni660
      run: |
        rm -r qmk_firmware/keyboards/sirius/uni660
        
    - name: Add define VIA_HAS_BROKEN_KEYCODES
      run: |
        directory="qmk_firmware/keyboards"
        for dir in $(ls -d ${directory}/*/); do
            if [ -d "${dir}keymaps/via" ]; then
                if grep -l "BLUETOOTH =" "${dir}rules.mk"; then
                    echo "#define VIA_HAS_BROKEN_KEYCODES" >> "${dir}config.h"
                fi
            fi
        done
      shell: bash
      
    - name: Remove ".noci"
      run: |
        find . -name ".noci" -type f -delete
        
    - name: ARM GCC version
      run: |
        which arm-none-eabi-gcc
        arm-none-eabi-gcc --version
        
    - name: Build
      working-directory: qmk_firmware
      #env:
      #  MAKEFLAGS: '-j3 --output-sync'
      run: |
        export PATH="/usr/local/sbin/avr-gcc-8.3.0-x64-linux/bin:$PATH"
        echo $PATH
        which avr-gcc
        avr-gcc --version
        git clean -xfd && make git-submodule && qmk mass-compile -j3 -km via || true
        # make all:via -j4 --output-sync
        cat .build/failed* > failures.log || true

    - name: 'Upload binaries'
      uses: actions/upload-artifact@v2
      with:
        name: Artifacts
        path: |
          qmk_firmware/failures.log 
        
    - name: Sort output
      shell: bash
      run: |
        for file in qmk_firmware/*.hex qmk_firmware/*.bin; do
          DIR=$(echo $(basename "$file")|cut -d'_' -f1)
          mkdir -p "$DIR"
          mv "$file" "$DIR/"
        done
        echo "Build on `date -u`" > README.md
      
    - name: Update Readme
      shell: bash "{0}"
      run: |
        echo -e "# VIA enabled QMK compiled HEX and BIN files\n\nThis has been compiled on $(git -C $PWD/qmk_firmware describe --abbrev=0 --tags)" > README.md

    - name: Add safe directory
      run: git config --global --add safe.directory /__w/QMK-VIA-Hex/QMK-VIA-Hex


    - name: Commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Nightly Build
